In [5]:
using Random, Plots
using Zygote, ForwardDiff
using OrdinaryDiffEq, DiffEqSensitivity
using LinearAlgebra
using Statistics
using ProgressBars, Printf
using Flux
using Flux.Optimise: update!
using Flux.Losses: mae, mse
using BSON: @save, @load
using DelimitedFiles
using YAML

In [6]:
pwd()

"C:\\Users\\Suraj\\Documents\\Biomass_run"

In [7]:
ENV["GKSwstype"] = "100"

"100"

In [14]:
conf = YAML.load_file("./config.yaml")

Dict{Any, Any} with 15 entries:
  "lr_max"        => 0.002
  "grad_max"      => 100.0
  "maxiters"      => 50000
  "n_epoch"       => 5000
  "lr_min"        => 1.0e-5
  "is_restart"    => false
  "lr_decay"      => 0.5
  "lr_decay_step" => 500
  "nc"            => 1
  "expr_name"     => "5s8r1c-01"
  "nr"            => 8
  "n_plot"        => 10
  "ns"            => 6
  "lb"            => 1.0e-8
  "w_decay"       => 1.0e-8

In [15]:
expr_name = conf["expr_name"]
fig_path = string("./results_catalyst/", expr_name, "/figs")
ckpt_path = string("./results_catalyst/", expr_name, "/checkpoint")
config_path = "./results_catalyst/$expr_name/config.yaml"

is_restart = Bool(conf["is_restart"])
ns = Int64(conf["ns"])
nr = Int64(conf["nr"])
nc = Int64(conf["nc"])
nss = Int64(conf["ns"]) - Int64(conf["nc"])
lb = Float64(conf["lb"])
n_epoch = Int64(conf["n_epoch"])
n_plot = Int64(conf["n_plot"])
grad_max = Float64(conf["grad_max"])
maxiters = Int64(conf["maxiters"])

lr_max = Float64(conf["lr_max"])
lr_min = Float64(conf["lr_min"])
lr_decay = Float64(conf["lr_decay"])
lr_decay_step = Int64(conf["lr_decay_step"])
w_decay = Float64(conf["w_decay"])

1.0e-8

In [16]:
llb = lb;
global p_cutoff = -1.0

const l_exp = 1:9
n_exp = length(l_exp)

l_train = []
l_val = []
for i = 1:n_exp
    j = l_exp[i]
    if !(j in [1,5,9])
        push!(l_train, i)
    else
        push!(l_val, i)
    end
end

opt = Flux.Optimiser(
 ExpDecay(lr_max, lr_decay, length(l_train) * lr_decay_step, lr_min),
 ADAMW(lr_max, (0.9, 0.999), w_decay),
);

#opt = Flux.Optimise.ADAMW(lr_max,(0.9,0.999), w_decay)

In [17]:
l_train, l_val, n_exp

(Any[2, 3, 4, 6, 7, 8], Any[1, 5, 9], 9)

In [18]:
if !is_restart
    if ispath(fig_path)
        rm(fig_path, recursive = true)
    end
    if ispath(ckpt_path)
        rm(ckpt_path, recursive = true)
    end
end

if ispath("./results_catalyst") == false
    mkdir("./results_catalyst")
end

if ispath("./results_catalyst/$expr_name") == false
    mkdir("./results_catalyst/$expr_name")
end

if ispath(fig_path) == false
    mkdir(fig_path)
    mkdir(string(fig_path, "/conditions"))
end

if ispath(ckpt_path) == false
    mkdir(ckpt_path)
end

cp("./config.yaml", config_path; force=true)

"./results_catalyst/5s8r1c-01/config.yaml"

In [19]:
function load_exp(filename)
    exp_data = readdlm(filename)  # [t, T, m]
    index = indexin(unique(exp_data[:, 1]), exp_data[:, 1])
    exp_data = exp_data[index, :]
    exp_data[:, 3] = exp_data[:, 3] / maximum(exp_data[:, 3])
    return exp_data
end

load_exp (generic function with 1 method)

In [20]:
l_exp_data = [];
l_exp_info = zeros(Float64, length(l_exp), 3);
for (i_exp, value) in enumerate(l_exp)
    filename = string("Exp_data5/expdata_no", string(value), ".txt")

    exp_data = Float64.(load_exp(filename))

    #exp_data = exp_data[1:80, :]
    
    # if value == 22
    #     exp_data = exp_data[1:90, :]
    # elseif value == 23
    #     exp_data = exp_data[1:100, :]
    # elseif value == 24
    #     exp_data = exp_data[1:100, :]
    #end

    push!(l_exp_data, exp_data)
    l_exp_info[i_exp, 1] = exp_data[1, 2] # initial temperature, K
end
l_exp_info[:, 2] = readdlm("Exp_data5/beta.txt")[l_exp];
l_exp_info[:, 3] = (readdlm("Exp_data5/cata_conc.txt")[l_exp]);

In [21]:
l_exp_data[4]

76×3 Matrix{Float64}:
    0.0  461.61  1.0
 1000.0  503.42  0.994208
 1250.0  513.9   0.988417
 1500.0  524.35  0.978764
 1600.0  528.47  0.974903
 1650.0  530.59  0.972973
 1700.0  532.67  0.969112
 1750.0  534.74  0.967181
 1800.0  536.8   0.96332
 1850.0  538.89  0.959459
 1900.0  540.95  0.955598
 1950.0  543.05  0.951737
 2000.0  545.12  0.947876
    ⋮            
 4718.0  658.32  0.214286
 4918.0  666.67  0.212355
 5118.0  675.01  0.210425
 5318.0  683.32  0.208494
 5518.0  691.63  0.206564
 5718.0  699.98  0.202703
 5918.0  708.29  0.200772
 6118.0  716.6   0.198842
 6318.0  724.9   0.194981
 6518.0  733.22  0.19305
 6718.0  741.57  0.19112
 6918.0  749.94  0.189189

In [22]:
l_exp_info

9×3 Matrix{Float64}:
 497.56   2.5  0.0
 523.22  10.0  0.0
 490.64   2.5  0.001
 461.61   2.5  0.01
 517.04  10.0  0.001
 490.7   10.0  0.01
 473.2    5.0  0.0
 473.17   5.0  0.001
 473.25   5.0  0.01

In [23]:
Random.seed!(12345)
np = nr * (ns + nc + 3) + 1
p = randn(Float64, np) .* 5.e-2;
p[1:nr] .+= 0.8;  # w_lnA
#p[nr*(nss+1)+1:nr*(ns+1)].*= 10            #w_cat_in
p[nr*(ns+1)+1:nr*(ns+nc+1)] .= 0         #w_cat_out
p[nr*(ns+nc+1)+1:nr*(ns+nc+2)] .+= 0.8;  # w_Ea
p[nr*(ns+nc+2)+1:nr*(ns+nc+3)] .+= 0.1;  # w_b
p[end] = 0.1;  #slope

In [24]:
function p2vec(p)
    slope = p[end] .* 1.e1
    w_b = p[1:nr] .* (slope * 10.0)
    w_b = clamp.(w_b, 0, 50)

    w_out = reshape(p[nr+1:nr*(nss+1)], nss, nr)
    @. w_out[1, :] = clamp(w_out[1, :], -3.0, 0.0)
    @. w_out[end, :] = clamp(abs(w_out[end, :]), 0.0, 3.0)

    if p_cutoff > 0.0
        w_out[findall(abs.(w_out) .< p_cutoff)] .= 0.0
    end

    w_out[nss-1:nss-1, :] .=
        -sum(w_out[1:nss-2, :], dims = 1) .- sum(w_out[nss:nss, :], dims = 1)

    w_cat_in = p[nr*(nss+1)+1:nr*(ns+1)]
    w_cat_out = p[nr*(ns+1)+1:nr*(ns+nc+1)]*0
    
    #w_cat_out = - sign.(w_cat_in) .* abs.(w_cat_out);
    w_cat_in = abs.(w_cat_in)
    
    
    if p_cutoff > 0.0
        w_cat_in[findall(abs.(w_cat_in) .< p_cutoff)] .= 0.0
    end
    
    w_in_Ea = abs.(p[nr*(ns+nc+1)+1:nr*(ns+nc+2)].* (slope * 100.0))
    w_in_Ea = clamp.(w_in_Ea, 0.0, 300.0)

    w_in_b = abs.(p[nr*(ns+nc+2)+1:nr*(ns+nc+3)])


    w_in = vcat(clamp.(-w_out, 0.0, 3.0), w_cat_in', w_in_Ea', w_in_b')
    w_out = vcat(w_out, w_cat_out')
    
    return w_in, w_b, w_out
end

p2vec (generic function with 1 method)

In [348]:
# expr_name1 = "5s8r1c-02"
# ckpt_path1 = string("./results_catalyst/", expr_name1, "/checkpoint")
# @load string(ckpt_path1, "/mymodel.bson") p

In [25]:
function display_p(p)
    w_in, w_b, w_out = p2vec(p)
    println("\n species (column) reaction (row)")
    println("w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out")
    show(stdout, "text/plain", round.(hcat(w_in', w_b, w_out'), digits = 2))
    # println("\n w_out")
    # show(stdout, "text/plain", round.(w_out', digits=3))
    println("\n")
end
display_p(p)


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.01  0.0   0.0   0.15  0.0  0.03  83.95  0.08  7.27  -0.01   0.02   0.03  -0.15  0.11  0.0
  0.01  0.08  0.04  0.0   0.0  0.07  80.93  0.06  7.79  -0.01  -0.08  -0.04   0.13  0.0   0.0
  0.01  0.1   0.05  0.0   0.0  0.02  72.92  0.12  8.42  -0.01  -0.1   -0.05   0.12  0.04  0.0
  0.0   0.01  0.06  0.0   0.0  0.06  68.25  0.11  8.21  -0.0   -0.01  -0.06   0.05  0.02  0.0
  0.05  0.0   0.05  0.0   0.0  0.01  81.05  0.01  7.51  -0.05   0.0   -0.05  -0.0   0.1   0.0
 -0.0   0.0   0.0   0.01  0.0  0.02  75.51  0.14  7.25   0.0   -0.0    0.01  -0.01  0.0   0.0
 -0.0   0.04  0.05  0.0   0.0  0.0   80.93  0.11  8.31   0.0   -0.04  -0.05   0.07  0.02  0.0
  0.09  0.03  0.0   0.0   0.0  0.03  84.52  0.05  7.3   -0.09  -0.03   0.03   0.06  0.02  0.0



In [26]:
function getsampletemp(t, T0, beta)
    
    T = clamp.((T0 + beta / 60 * t), 0, 873.15)   # K/min to K/s

    return T
end

getsampletemp (generic function with 1 method)

In [27]:
const R = -1.0 / 8.314e-3  # universal gas constant, kJ/mol*K
@inbounds function crnn!(du, u, p, t)
    logX = @. log(clamp(u, lb, 10.0))
    T = getsampletemp(t, T0, beta)
    w_in_x = w_in' * vcat(logX, R / T, log(T))
    du .= w_out * (@. exp(w_in_x + w_b))
end

crnn! (generic function with 1 method)

In [28]:
tspan = [0.0, 1.0];
u0 = zeros(ns);
u0[1] = 1.0;
prob = ODEProblem(crnn!, u0, tspan, p, abstol = lb)

ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
timespan: (0.0, 1.0)
u0: 6-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [29]:
condition(u, t, integrator) = u[1] < lb * 10.0
affect!(integrator) = terminate!(integrator)
_cb = DiscreteCallback(condition, affect!)

alg = TRBDF2();
#alg = RK4();
#alg = TRBDF2();
#alg = AutoTsit5(Rosenbrock23(autodiff=false));
#alg = Rosenbrock23(autodiff=false);
#alg = AutoVern7(Rodas5P(autodiff = false));
#sense = BacksolveAdjoint(checkpointing=true; autojacvec=ZygoteVJP());
sense = ForwardSensitivity(autojacvec = true)

ForwardSensitivity{0, true, Val{:central}}(true, false)

In [30]:
function pred_n_ode(p, i_exp, exp_data)
    global T0, beta, cat_conc = l_exp_info[i_exp, :]
    global w_in, w_b, w_out = p2vec(p)

    ts = @view(exp_data[:, 1])
    tspan = [ts[1], ts[end]]
    u0[end] = cat_conc 
    sol = solve(
        prob,
        alg,
        tspan = tspan,
        p = p,
        saveat = ts, 
        sensealg = sense,
        maxiters = maxiters
        # callback = _cb,
    )

    if sol.retcode == :Success
        nothing
    else
        #@sprintf("solver failed beta: %.0f ocen: %.2f", beta, exp(ocen))
        @sprintf("solver failed beta: %.0f", beta)
    end
    if length(sol.t) > length(ts)
        # @show exp_data[:, 1]
        # @show sol.t
        return  sol[:, 1:length(ts)]
    else
        return sol
    end
end

pred_n_ode (generic function with 1 method)

In [31]:
function loss_neuralode(p, i_exp)
    exp_data = l_exp_data[i_exp]
    pred = Array(pred_n_ode(p, i_exp, exp_data))
    masslist = sum(clamp.(@view(pred[1:end-1-nc, :]), 0, Inf), dims = 1)'
    gaslist = clamp.(@views(pred[end-nc, :]), 0,  Inf)

    loss = mae(masslist, @view(exp_data[1:length(masslist), 3])) + mae(gaslist, 1 .- @view(exp_data[1:length(masslist), 3]))
    return loss
end

loss_neuralode (generic function with 1 method)

In [356]:
# function loss_neuralode(p, i_exp)
#     exp_data = l_exp_data[i_exp]
#     pred = Array(pred_n_ode(p, i_exp, exp_data))
#     masslist = sum(clamp.(@view(pred[1:end-1-nc, :]), 0, Inf), dims = 1)'
#     gaslist = clamp.(@views(pred[end-nc, :]), 0,  Inf)

#     loss = mse(masslist, @view(exp_data[1:length(masslist), 3])) + mse(gaslist, 1 .- @view(exp_data[1:length(masslist), 3]))
#     return loss
# end

In [32]:
@time loss = loss_neuralode(p, 1)

 16.619802 seconds (45.09 M allocations: 2.649 GiB, 6.86% gc time, 99.58% compilation time)


1.1469355162922197

In [358]:
function plot_sol(i_exp, sol, exp_data, Tlist, cap, sol0 = nothing)
    T0, beta, cat = l_exp_info[i_exp, :]
    #T0, beta = l_exp_info[i_exp, :]
    ts = sol.t / 60.0
    ind = length(ts)
    plt = plot(
        exp_data[:, 1] / 60.0,
        exp_data[:, 3],
        seriestype = :scatter,
        label = "Exp",
    )

    plot!(
        plt,
        ts,
        sum(clamp.(sol[1:end-1-nc, :], 0, Inf), dims = 1)',
        lw = 3,
        legend = :left,
        label = "CRNN",
    )
    
    if sol0 !== nothing
        plot!(
            plt,
            sol0.t / 60,
            sum(sol0[1:end-1-nc, :], dims = 1)',
            label = "initial model",
        )
    end
    xlabel!(plt, "Time [min]")
    ylabel!(plt, "Mass")
    ylims!(0,1.1)
    title!(plt, cap)
    exp_cond = string(
        @sprintf(
            #"T0 = %.1f K \n beta = %.2f K/min",
            "T0 = %.1f K \n beta = %.2f K/min \n [catalyst] = %.2f",
            T0,
            beta,
            cat*100
        )
    )
    annotate!(plt, exp_data[end, 1] / 60.0 * 0.85, 0.4, exp_cond)

    plt2 = twinx()
    plot!(
        plt2,
        exp_data[1:ind, 1] / 60,
        Tlist,
        lw = 2,
        ls = :dash,
        legend = :topright,
        label = "T",
    )
    ylabel!(plt2, "Temp")

    p2 = plot(ts, sol[1, :], lw = 2, legend = :right, label = "Cellulose")
    for i = 2:ns-nc
        plot!(p2, ts, sol[i, :], lw = 2, label = "S$i")
    end
    xlabel!(p2, "Time [min]")
    ylabel!(p2, "Mass")

    plt = plot(plt, p2, framestyle = :box, layout = @layout [a; b])
    plot!(plt, size = (800, 800))
    return plt
end

cbi = function (p, i_exp)
    exp_data = l_exp_data[i_exp]
    sol = pred_n_ode(p, i_exp, exp_data)
    Tlist = similar(sol.t)
    #T0, beta, ocen = l_exp_info[i_exp, :]
    T0, beta = l_exp_info[i_exp, :]
    for (i, t) in enumerate(sol.t)
        Tlist[i] = getsampletemp(t, T0, beta)
    end
    value = l_exp[i_exp]
    plt = plot_sol(i_exp, sol, exp_data, Tlist, "exp_$value")
    png(plt, string(fig_path, "/conditions/pred_exp_$value"))
    return false
end


function plot_loss(l_loss_train, l_loss_val; yscale = :log10)
    plt_loss = plot(l_loss_train, yscale = yscale, label = "train")
    plot!(plt_loss, l_loss_val, yscale = yscale, label = "val")
    plt_grad = plot(list_grad, yscale = yscale, label = "grad_norm")
    xlabel!(plt_loss, "Epoch")
    ylabel!(plt_loss, "Loss")
    xlabel!(plt_grad, "Epoch")
    ylabel!(plt_grad, "Gradient Norm")
    # ylims!(plt_loss, (-Inf, 1e0))
    # ylims!(plt_grad, (-Inf, 1e3))
    #plt_all = plot([plt_loss, plt_grad]..., legend = :top, framestyle=:box)
    # plot!(
    #     plt_all,
    #     size=(800, 400),
    #     xtickfontsize = 11,
    #     ytickfontsize = 11,
    #     xguidefontsize = 12,
    #     yguidefontsize = 12,
    # )
    png(plt_loss, string(fig_path, "/loss_plot"))
    png(plt_grad, string(fig_path, "/grad_plot"))
end

l_loss_train = []
l_loss_val = []
list_grad = []
iter = 1
cb = function (p, loss_train, loss_val, g_norm)
    global l_loss_train, l_loss_val, list_grad, iter
    push!(l_loss_train, loss_train)
    push!(l_loss_val, loss_val)
    push!(list_grad, g_norm)

    #if iter % n_plot == 0
    if all(x -> loss_val < x, l_loss_val[1:end-1])
        display_p(p)
        list_exp = randperm(n_exp)[1]
        @printf(
            "Min Loss train: %.2e val: %.2e",
            minimum(l_loss_train),
            minimum(l_loss_val)
        )
        println("\n update plot ", l_exp[list_exp], "\n")
        for i_exp in list_exp
            cbi(p, i_exp)
        end
        @save string(ckpt_path, "/mymodel.bson") p opt l_loss_train l_loss_val list_grad iter
    end
    
    plot_loss(l_loss_train, l_loss_val; yscale = :log10)
    iter += 1 
end

if is_restart
    @load string(ckpt_path, "/mymodel.bson") p opt l_loss_train l_loss_val list_grad iter
    iter += 1
end

In [359]:
epochs = ProgressBar(iter:n_epoch);
loss_epoch = zeros(Float64, n_exp);
grad_norm = zeros(Float64, n_exp);
for epoch in epochs
    global p
    for i_exp in randperm(n_exp)
        if i_exp in l_val
            continue
        end
        grad = ForwardDiff.gradient(x -> loss_neuralode(x, i_exp), p)
        grad_norm[i_exp] = norm(grad, 2)
        if grad_norm[i_exp] > grad_max
            grad = grad ./ grad_norm[i_exp] .* grad_max
        end
        update!(opt, p, grad)
    end
    for i_exp = 1:n_exp
        loss_epoch[i_exp] = loss_neuralode(p, i_exp)
    end
    loss_train = mean(loss_epoch[l_train])
    loss_val = mean(loss_epoch[l_val])
    grad_mean = mean(grad_norm[l_train])
    set_description(
        epochs,
        string(
            @sprintf(
                "Loss train: %.2e val: %.2e grad: %.2e lr: %.1e",
                loss_train,
                loss_val,
                grad_mean,
                opt[1].eta
                #opt.eta
            )
        ),
    )
    cb(p, loss_train, loss_val, grad_mean)
end

conf["loss_train"] = minimum(l_loss_train)
conf["loss_val"] = minimum(l_loss_val)
YAML.write_file(config_path, conf)

0.0%┣                                             ┫ 0/2.5k [00:00<00:-7, -0s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.04  0.01  0.06  0.0   0.0  0.08  70.3   0.08  7.1   -0.04  -0.01  -0.06   0.09  0.01  0.0
  0.03  0.0   0.0   0.03  0.0  0.04  70.74  0.11  7.6   -0.03   0.0   -0.0   -0.03  0.06  0.0
  0.02  0.04  0.02  0.0   0.0  0.02  79.11  0.05  7.66  -0.02  -0.04  -0.02   0.05  0.04  0.0
  0.01  0.11  0.01  0.0   0.0  0.04  81.38  0.06  6.9   -0.01  -0.11  -0.01   0.1   0.03  0.0
 -0.0   0.03  0.0   0.04  0.0  0.01  81.15  0.07  7.44   0.0   -0.03   0.05  -0.04  0.02  0.0
  0.01  0.02  0.0   0.0   0.0  0.06  71.12  0.16  7.07  -0.01  -0.02   0.01  -0.0   0.02  0.0
 -0.0   0.04  0.0   0.06  0.0  0.01  72.75  0.12  7.73   0.0   -0.04   0.05  -0.06  0.05  0.0
  0.05  0.02  0.02  0.01  0.0  0.08  65.95  0.08  6.93  -0.05  -0.02  -0.02  -0.01  0.1   0.0

Min Loss train: 7.56e-01 val: 7.27e-01
 update plot 6



Loss train: 7.56e-01 val: 7.27e-01 grad: 8.86e+00 lr: 2.0e-03 0.0%┣┫ 1/2.5k [00:26<Inf:Inf, InfGs/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.05  0.0   0.05  0.0   0.0  0.07  65.32  0.08  6.67  -0.05  -0.0   -0.05   0.09  0.01  0.0
  0.04  0.0   0.0   0.01  0.0  0.03  65.64  0.12  7.14  -0.04   0.01  -0.0   -0.01  0.05  0.0
  0.03  0.04  0.02  0.0   0.0  0.02  74.04  0.04  7.14  -0.03  -0.04  -0.02   0.06  0.04  0.0
  0.02  0.12  0.01  0.0   0.0  0.05  76.51  0.05  6.4   -0.02  -0.12  -0.01   0.12  0.03  0.0
 -0.0   0.02  0.0   0.05  0.0  0.01  76.1   0.07  6.92   0.0   -0.02   0.06  -0.05  0.02  0.0
  0.02  0.01  0.0   0.0   0.0  0.05  66.63  0.16  6.58  -0.02  -0.01   0.01   0.0   0.02  0.0
 -0.0   0.04  0.0   0.08  0.0  0.01  68.15  0.12  7.2    0.0   -0.04   0.06  -0.08  0.06  0.0
  0.06  0.02  0.02  0.0   0.0  0.08  61.16  0.08  6.52  -0.06  -0.02  -0.02  -0.0   0.1   0.0

Min Loss train: 6.35e-01 val: 5.98e-01
 update plot 7



Loss train: 6.35e-01 val: 5.98e-01 grad: 1.16e+01 lr: 2.0e-03 0.1%┣┫ 2/2.5k [00:27<18:32:08, 27s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.05  0.0   0.04  0.0   0.0  0.08  65.76  0.08  6.67  -0.05   0.0   -0.04   0.08  0.01  0.0
  0.05  0.0   0.0   0.01  0.0  0.03  65.72  0.12  7.17  -0.05   0.01   0.0   -0.01  0.05  0.0
  0.04  0.04  0.02  0.0   0.0  0.03  74.92  0.04  7.1   -0.04  -0.04  -0.02   0.07  0.03  0.0
  0.03  0.13  0.02  0.0   0.0  0.06  77.45  0.04  6.36  -0.03  -0.13  -0.02   0.15  0.03  0.0
 -0.0   0.02  0.0   0.07  0.0  0.01  76.61  0.07  6.93   0.0   -0.02   0.07  -0.07  0.01  0.0
  0.03  0.0   0.0   0.0   0.0  0.05  67.24  0.15  6.56  -0.03  -0.0    0.02  -0.0   0.01  0.0
 -0.0   0.03  0.0   0.1   0.0  0.01  68.69  0.12  7.2    0.0   -0.03   0.07  -0.1   0.06  0.0
  0.07  0.01  0.01  0.01  0.0  0.08  61.48  0.08  6.52  -0.07  -0.01  -0.01  -0.01  0.1   0.0

Min Loss train: 5.64e-01 val: 5.23e-01
 update plot 8



Loss train: 5.64e-01 val: 5.23e-01 grad: 1.82e+01 lr: 2.0e-03 0.1%┣┫ 3/2.5k [00:28<09:40:49, 14s/it]
Loss train: 5.80e-01 val: 5.77e-01 grad: 1.75e+01 lr: 2.0e-03 0.2%┣┫ 4/2.5k [00:29<06:36:02, 10s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.06  0.0   0.04  0.0   0.0  0.07  67.71  0.08  6.83  -0.06   0.0   -0.04   0.1   0.0   0.0
  0.06  0.0   0.0   0.02  0.0  0.03  67.84  0.11  7.31  -0.06   0.02   0.01  -0.02  0.05  0.0
  0.05  0.06  0.02  0.0   0.0  0.02  76.64  0.04  7.32  -0.05  -0.06  -0.02   0.12  0.02  0.0
  0.04  0.14  0.01  0.0   0.0  0.04  78.63  0.06  6.62  -0.04  -0.14  -0.01   0.18  0.01  0.0
 -0.0   0.02  0.0   0.07  0.0  0.02  79.16  0.06  7.06   0.0   -0.02   0.08  -0.07  0.01  0.0
  0.03  0.01  0.0   0.0   0.0  0.06  69.51  0.15  6.68  -0.03  -0.01   0.02   0.01  0.01  0.0
 -0.0   0.03  0.0   0.11  0.0  0.02  71.19  0.11  7.32   0.0   -0.03   0.08  -0.11  0.06  0.0
  0.07  0.01  0.0   0.02  0.0  0.07  63.51  0.07  6.64  -0.07  -0.01  -0.0   -0.02  0.1   0.0

Min Loss train: 5.21e-01 val: 5.02e-01
 update plot 6



Loss train: 5.21e-01 val: 5.02e-01 grad: 1.29e+01 lr: 2.0e-03 0.2%┣┫ 5/2.5k [00:30<05:06:52, 7s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.07  0.0   0.04  0.0   0.0  0.07  66.8   0.07  6.72  -0.07   0.0   -0.04   0.11  0.0   0.0
  0.06  0.0   0.0   0.01  0.0  0.02  66.76  0.11  7.21  -0.06   0.02   0.01  -0.01  0.05  0.0
  0.06  0.07  0.02  0.0   0.0  0.01  75.33  0.04  7.22  -0.06  -0.07  -0.02   0.13  0.02  0.0
  0.05  0.15  0.01  0.0   0.0  0.04  77.11  0.06  6.56  -0.05  -0.15  -0.01   0.2   0.01  0.0
 -0.0   0.01  0.0   0.08  0.0  0.03  78.11  0.06  6.94   0.0   -0.01   0.08  -0.08  0.01  0.0
  0.04  0.01  0.0   0.0   0.0  0.06  68.62  0.15  6.56  -0.04  -0.01   0.02   0.02  0.01  0.0
 -0.0   0.02  0.0   0.12  0.0  0.03  70.3   0.1   7.19   0.0   -0.02   0.08  -0.12  0.06  0.0
  0.08  0.01  0.0   0.01  0.0  0.07  62.58  0.07  6.54  -0.08  -0.01  -0.0   -0.01  0.1   0.0

Min Loss train: 5.01e-01 val: 4.68e-01
 update plot 5



Loss train: 5.01e-01 val: 4.68e-01 grad: 1.68e+01 lr: 2.0e-03 0.2%┣┫ 6/2.5k [00:31<04:13:45, 6s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.08  0.0   0.04  0.0   0.0  0.07  67.24  0.07  6.69  -0.08   0.01  -0.04   0.11  0.0   0.0
  0.06  0.0   0.0   0.02  0.0  0.02  66.84  0.11  7.21  -0.06   0.02   0.01  -0.02  0.05  0.0
  0.07  0.08  0.02  0.0   0.0  0.01  75.41  0.04  7.23  -0.07  -0.08  -0.02   0.15  0.02  0.0
  0.05  0.16  0.01  0.0   0.0  0.03  77.02  0.06  6.59  -0.05  -0.16  -0.01   0.21  0.0   0.0
 -0.0   0.01  0.0   0.09  0.0  0.03  78.25  0.06  6.95   0.0   -0.01   0.08  -0.09  0.01  0.0
  0.04  0.01  0.0   0.0   0.0  0.06  69.06  0.14  6.54  -0.04  -0.01   0.02   0.02  0.01  0.0
 -0.0   0.02  0.0   0.13  0.0  0.03  70.34  0.11  7.21   0.0   -0.02   0.08  -0.13  0.07  0.0
  0.08  0.01  0.0   0.02  0.0  0.07  62.65  0.07  6.55  -0.08  -0.01   0.0   -0.02  0.11  0.0

Min Loss train: 4.82e-01 val: 4.53e-01
 update plot 3




Loss train: 4.82e-01 val: 4.53e-01 grad: 1.87e+01 lr: 2.0e-03 0.3%┣┫ 7/2.5k [00:31<03:37:44, 5s/it]
Loss train: 4.96e-01 val: 4.98e-01 grad: 1.70e+01 lr: 2.0e-03 0.3%┣┫ 8/2.5k [00:32<03:12:47, 5s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.1   0.0   0.04  0.0   0.0  0.06  67.39  0.07  6.69  -0.1    0.01  -0.04   0.13  0.0   0.0
  0.07  0.0   0.0   0.02  0.0  0.02  67.18  0.11  7.19  -0.07   0.02   0.01  -0.02  0.06  0.0
  0.08  0.08  0.03  0.0   0.0  0.0   74.86  0.05  7.31  -0.08  -0.08  -0.03   0.17  0.02  0.0
  0.04  0.16  0.02  0.0   0.0  0.02  76.4   0.07  6.68  -0.04  -0.16  -0.02   0.22  0.0   0.0
 -0.0   0.01  0.0   0.09  0.0  0.04  78.7   0.06  6.94   0.0   -0.01   0.09  -0.09  0.01  0.0
  0.03  0.02  0.0   0.0   0.0  0.07  69.79  0.13  6.48  -0.03  -0.02   0.02   0.02  0.01  0.0
 -0.0   0.02  0.0   0.14  0.0  0.04  70.69  0.1   7.2    0.0   -0.02   0.08  -0.14  0.07  0.0
  0.09  0.01  0.0   0.01  0.0  0.06  62.75  0.07  6.55  -0.09  -0.01  -0.0   -0.01  0.11  0.0

Min Loss train: 4.49e-01 val: 4.06e-01
 update plot 3




Loss train: 4.49e-01 val: 4.06e-01 grad: 1.44e+01 lr: 2.0e-03 0.4%┣┫ 9/2.5k [00:34<02:54:46, 4s/it]
Loss train: 4.35e-01 val: 4.13e-01 grad: 1.69e+01 lr: 2.0e-03 0.4%┣┫ 10/2.5k [00:35<02:40:14, 4s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.11  0.0   0.04  0.0   0.0  0.05  67.54  0.07  6.68  -0.11   0.01  -0.04   0.15  0.0   0.0
  0.07  0.0   0.0   0.03  0.0  0.01  67.46  0.1   7.17  -0.07   0.03   0.01  -0.03  0.07  0.0
  0.09  0.08  0.04  0.0   0.0  0.01  74.52  0.05  7.36  -0.09  -0.08  -0.04   0.18  0.02  0.0
  0.04  0.16  0.02  0.0   0.0  0.02  76.15  0.07  6.72  -0.04  -0.16  -0.02   0.21  0.01  0.0
 -0.0   0.01  0.0   0.09  0.0  0.05  78.74  0.06  6.95   0.0   -0.01   0.09  -0.09  0.01  0.0
  0.03  0.02  0.0   0.0   0.0  0.08  70.29  0.13  6.44  -0.03  -0.02   0.02   0.03  0.01  0.0
 -0.0   0.02  0.0   0.14  0.0  0.04  70.72  0.11  7.22   0.0   -0.02   0.08  -0.14  0.07  0.0
  0.09  0.01  0.0   0.01  0.0  0.05  62.93  0.07  6.55  -0.09  -0.01   0.0   -0.01  0.11  0.0

Min Loss train: 4.18e-01 val: 3.79e-01
 update plot 6



Loss train: 4.18e-01 val: 3.79e-01 grad: 1.50e+01 lr: 2.0e-03 0.4%┣┫ 11/2.5k [00:36<02:28:06, 4s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.12  0.0   0.04  0.0   0.0  0.05  67.54  0.07  6.68  -0.12   0.01  -0.04   0.15  0.0   0.0
  0.07  0.0   0.0   0.04  0.0  0.01  67.53  0.1   7.17  -0.07   0.03   0.01  -0.04  0.07  0.0
  0.09  0.08  0.04  0.0   0.0  0.0   74.3   0.05  7.38  -0.09  -0.08  -0.04   0.19  0.02  0.0
  0.04  0.16  0.03  0.0   0.0  0.02  76.01  0.08  6.73  -0.04  -0.16  -0.03   0.22  0.01  0.0
 -0.0   0.01  0.0   0.09  0.0  0.05  78.81  0.06  6.95   0.0   -0.01   0.09  -0.09  0.01  0.0
  0.03  0.02  0.0   0.0   0.0  0.08  70.47  0.12  6.42  -0.03  -0.02   0.02   0.03  0.01  0.0
 -0.0   0.02  0.0   0.14  0.0  0.05  70.76  0.11  7.23   0.0   -0.02   0.09  -0.14  0.07  0.0
  0.09  0.01  0.0   0.02  0.0  0.04  63.03  0.07  6.54  -0.09  -0.01   0.01  -0.02  0.12  0.0

Min Loss train: 4.04e-01 val: 3.68e-01
 update plot 9




Loss train: 4.04e-01 val: 3.68e-01 grad: 2.32e+01 lr: 2.0e-03 0.5%┣┫ 12/2.5k [00:37<02:18:44, 3s/it]
Loss train: 4.09e-01 val: 4.05e-01 grad: 1.30e+01 lr: 2.0e-03 0.5%┣┫ 13/2.5k [00:38<02:10:20, 3s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.13  0.0   0.03  0.0   0.0  0.05  67.73  0.06  6.72  -0.13   0.01  -0.03   0.15  0.0   0.0
  0.07  0.0   0.0   0.05  0.0  0.0   67.91  0.1   7.18  -0.07   0.03   0.01  -0.05  0.07  0.0
  0.1   0.08  0.04  0.0   0.0  0.0   74.25  0.06  7.44  -0.1   -0.08  -0.04   0.2   0.03  0.0
  0.04  0.16  0.03  0.0   0.0  0.01  76.18  0.08  6.78  -0.04  -0.16  -0.03   0.22  0.01  0.0
 -0.0   0.01  0.0   0.11  0.0  0.06  79.31  0.05  6.96   0.0   -0.01   0.1   -0.11  0.02  0.0
  0.03  0.03  0.0   0.0   0.0  0.08  71.08  0.12  6.41  -0.03  -0.03   0.02   0.04  0.0   0.0
 -0.0   0.02  0.0   0.16  0.0  0.05  71.1   0.11  7.25   0.0   -0.02   0.09  -0.16  0.08  0.0
  0.1   0.01  0.0   0.03  0.0  0.04  63.51  0.06  6.54  -0.1   -0.01   0.01  -0.03  0.12  0.0

Min Loss train: 3.84e-01 val: 3.61e-01
 update plot 9



Loss train: 3.84e-01 val: 3.61e-01 grad: 1.50e+01 lr: 2.0e-03 0.6%┣┫ 14/2.5k [00:39<02:03:31, 3s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.13  0.0   0.03  0.0   0.0  0.04  67.02  0.06  6.65  -0.13   0.01  -0.03   0.15  0.01  0.0
  0.07  0.0   0.0   0.06  0.0  0.0   67.21  0.1   7.11  -0.07   0.04   0.02  -0.06  0.08  0.0
  0.1   0.09  0.04  0.0   0.0  0.0   73.18  0.06  7.39  -0.1   -0.09  -0.04   0.2   0.03  0.0
  0.04  0.16  0.03  0.0   0.0  0.0   75.03  0.08  6.74  -0.04  -0.16  -0.03   0.22  0.02  0.0
 -0.0   0.01  0.0   0.11  0.0  0.06  78.49  0.05  6.89   0.0   -0.01   0.1   -0.11  0.02  0.0
  0.03  0.03  0.0   0.0   0.0  0.08  70.49  0.12  6.33  -0.03  -0.03   0.02   0.04  0.0   0.0
 -0.0   0.02  0.0   0.16  0.0  0.05  70.25  0.11  7.19   0.0   -0.02   0.1   -0.16  0.08  0.0
  0.1   0.01  0.0   0.03  0.0  0.03  62.82  0.06  6.48  -0.1   -0.01   0.02  -0.03  0.13  0.0

Min Loss train: 3.70e-01 val: 3.34e-01
 update plot 3



Loss train: 3.70e-01 val: 3.34e-01 grad: 1.91e+01 lr: 2.0e-03 0.6%┣┫ 15/2.5k [00:40<01:57:47, 3s/it]
Loss train: 3.63e-01 val: 3.41e-01 grad: 1.77e+01 lr: 2.0e-03 0.6%┣┫ 16/2.5k [00:41<01:52:13, 3s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.14  0.0   0.03  0.0   0.0  0.04  66.8   0.07  6.65  -0.14   0.01  -0.03   0.16  0.0   0.0
  0.07  0.0   0.0   0.07  0.0  0.0   67.21  0.1   7.09  -0.07   0.04   0.02  -0.07  0.08  0.0
  0.11  0.09  0.05  0.0   0.0  0.0   72.47  0.07  7.44  -0.11  -0.09  -0.05   0.21  0.03  0.0
  0.04  0.16  0.04  0.0   0.0  0.01  74.52  0.09  6.77  -0.04  -0.16  -0.04   0.22  0.02  0.0
 -0.0   0.01  0.0   0.12  0.0  0.07  78.71  0.05  6.84   0.0   -0.01   0.11  -0.12  0.02  0.0
  0.03  0.03  0.0   0.0   0.0  0.09  70.69  0.11  6.29  -0.03  -0.03   0.02   0.04  0.0   0.0
 -0.0   0.01  0.0   0.17  0.0  0.05  70.34  0.1   7.16   0.0   -0.01   0.1   -0.17  0.08  0.0
  0.1   0.01  0.0   0.05  0.0  0.03  62.91  0.06  6.45  -0.1   -0.01   0.02  -0.05  0.14  0.0

Min Loss train: 3.48e-01 val: 3.04e-01
 update plot 6


Loss train: 3.48e-01 val: 3.04e-01 grad: 1.78e+01 lr: 2.0e-03 0.7%┣┫ 17/2.5k [00:42<01:47:23, 3s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.15  0.0   0.03  0.0   0.0  0.03  66.74  0.06  6.63  -0.15   0.01  -0.03   0.16  0.0   0.0
  0.07  0.0   0.0   0.07  0.0  0.0   67.04  0.1   7.07  -0.07   0.04   0.02  -0.07  0.09  0.0
  0.12  0.09  0.05  0.0   0.0  0.0   72.18  0.07  7.43  -0.12  -0.09  -0.05   0.22  0.04  0.0
  0.04  0.17  0.04  0.0   0.0  0.0   74.3   0.09  6.76  -0.04  -0.17  -0.04   0.23  0.03  0.0
 -0.0   0.01  0.0   0.13  0.0  0.07  78.48  0.05  6.83   0.0   -0.01   0.11  -0.13  0.02  0.0
  0.03  0.03  0.0   0.0   0.0  0.09  70.76  0.11  6.25  -0.03  -0.03   0.02   0.04  0.0   0.0
 -0.0   0.01  0.0   0.18  0.0  0.05  70.0   0.11  7.16   0.0   -0.01   0.11  -0.18  0.09  0.0
  0.1   0.01  0.0   0.05  0.0  0.02  62.77  0.06  6.44  -0.1   -0.01   0.02  -0.05  0.14  0.0

Min Loss train: 3.39e-01 val: 2.92e-01
 update plot 2



Loss train: 3.39e-01 val: 2.92e-01 grad: 2.07e+01 lr: 2.0e-03 0.7%┣┫ 18/2.5k [00:43<01:43:43, 3s/it]
Loss train: 3.35e-01 val: 3.06e-01 grad: 2.58e+01 lr: 2.0e-03 0.8%┣┫ 19/2.5k [00:43<01:39:52, 2s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.16  0.0   0.02  0.0   0.0  0.03  67.31  0.06  6.69  -0.16   0.01  -0.02   0.17  0.0   0.0
  0.08  0.0   0.0   0.08  0.0  0.0   67.71  0.09  7.12  -0.08   0.05   0.02  -0.08  0.09  0.0
  0.13  0.09  0.05  0.0   0.0  0.0   72.34  0.07  7.54  -0.13  -0.09  -0.05   0.23  0.04  0.0
  0.04  0.17  0.05  0.0   0.0  0.0   74.6   0.09  6.84  -0.04  -0.17  -0.05   0.24  0.03  0.0
 -0.0   0.0   0.0   0.14  0.0  0.07  79.33  0.05  6.86   0.0   -0.0    0.12  -0.14  0.02  0.0
  0.04  0.03  0.0   0.0   0.0  0.09  71.61  0.11  6.27  -0.04  -0.03   0.02   0.05  0.0   0.0
 -0.0   0.01  0.0   0.2   0.0  0.06  70.56  0.11  7.21   0.0   -0.01   0.12  -0.2   0.09  0.0
  0.11  0.0   0.0   0.06  0.0  0.01  63.45  0.06  6.48  -0.11  -0.0    0.03  -0.06  0.15  0.0

Min Loss train: 3.23e-01 val: 2.86e-01
 update plot 8



Loss train: 3.23e-01 val: 2.86e-01 grad: 1.79e+01 lr: 2.0e-03 0.8%┣┫ 20/2.5k [00:45<01:36:50, 2s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.16  0.0   0.02  0.0   0.0  0.02  67.08  0.06  6.65  -0.16   0.01  -0.02   0.17  0.0   0.0
  0.08  0.0   0.0   0.09  0.0  0.0   67.39  0.09  7.09  -0.08   0.05   0.02  -0.09  0.09  0.0
  0.14  0.09  0.05  0.0   0.0  0.0   71.96  0.07  7.51  -0.14  -0.09  -0.05   0.24  0.04  0.0
  0.04  0.18  0.05  0.0   0.0  0.0   74.24  0.09  6.82  -0.04  -0.18  -0.05   0.24  0.03  0.0
 -0.0   0.0   0.0   0.15  0.0  0.08  78.92  0.05  6.84   0.0   -0.0    0.13  -0.15  0.02  0.0
  0.04  0.03  0.0   0.0   0.0  0.1   71.44  0.11  6.23  -0.04  -0.03   0.02   0.05  0.0   0.0
 -0.0   0.01  0.0   0.2   0.0  0.06  70.08  0.11  7.2    0.0   -0.01   0.12  -0.2   0.09  0.0
  0.11  0.0   0.0   0.07  0.0  0.01  63.15  0.06  6.45  -0.11  -0.0    0.03  -0.07  0.15  0.0

Min Loss train: 3.14e-01 val: 2.68e-01
 update plot 7



Loss train: 3.14e-01 val: 2.68e-01 grad: 2.23e+01 lr: 2.0e-03 0.8%┣┫ 21/2.5k [00:45<01:33:56, 2s/it]
Loss train: 3.12e-01 val: 2.72e-01 grad: 2.49e+01 lr: 2.0e-03 0.9%┣┫ 22/2.5k [00:46<01:31:05, 2s/it]
Loss train: 3.02e-01 val: 2.69e-01 grad: 1.85e+01 lr: 2.0e-03 0.9%┣┫ 23/2.5k [00:47<01:28:24, 2s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.17  0.0   0.02  0.0   0.0  0.01  67.35  0.06  6.67  -0.17   0.01  -0.02   0.18  0.0   0.0
  0.08  0.0   0.0   0.1   0.0  0.0   67.71  0.09  7.11  -0.08   0.05   0.02  -0.1   0.1   0.0
  0.15  0.09  0.05  0.0   0.0  0.0   71.83  0.08  7.58  -0.15  -0.09  -0.05   0.25  0.05  0.0
  0.03  0.18  0.06  0.0   0.0  0.01  74.37  0.09  6.85  -0.03  -0.18  -0.06   0.24  0.03  0.0
 -0.0   0.0   0.0   0.16  0.0  0.08  79.09  0.05  6.86   0.0   -0.0    0.14  -0.16  0.03  0.0
  0.04  0.03  0.0   0.0   0.0  0.1   71.94  0.1   6.22  -0.04  -0.03   0.02   0.05  0.0   0.0
 -0.0   0.01  0.0   0.21  0.0  0.06  69.95  0.11  7.24   0.0   -0.01   0.13  -0.21  0.1   0.0
  0.11  0.0   0.0   0.08  0.0  0.0   63.5   0.06  6.46  -0.11  -0.0    0.03  -0.08  0.16  0.0

Min Loss train: 2.99e-01 val: 2.54e-01
 update plot 1



Loss train: 2.99e-01 val: 2.54e-01 grad: 2.52e+01 lr: 2.0e-03 1.0%┣┫ 24/2.5k [00:48<01:26:14, 2s/it]
Loss train: 3.12e-01 val: 3.02e-01 grad: 2.10e+01 lr: 2.0e-03 1.0%┣┫ 25/2.5k [00:49<01:24:07, 2s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.18  0.0   0.02  0.0   0.0  0.01  67.49  0.06  6.64  -0.18   0.01  -0.02   0.18  0.01  0.0
  0.08  0.0   0.0   0.11  0.0  0.0   67.61  0.09  7.1   -0.08   0.06   0.02  -0.11  0.11  0.0
  0.16  0.09  0.06  0.0   0.0  0.0   71.69  0.08  7.58  -0.16  -0.09  -0.06   0.25  0.06  0.0
  0.03  0.19  0.07  0.0   0.0  0.01  74.18  0.09  6.85  -0.03  -0.19  -0.07   0.24  0.04  0.0
 -0.0   0.0   0.0   0.17  0.0  0.08  78.91  0.05  6.86   0.0   -0.0    0.14  -0.17  0.03  0.0
  0.04  0.04  0.0   0.0   0.0  0.11  72.15  0.1   6.18  -0.04  -0.04   0.02   0.06  0.0   0.0
 -0.0   0.01  0.0   0.22  0.0  0.06  69.46  0.11  7.27   0.0   -0.01   0.13  -0.22  0.1   0.0
  0.11  0.0   0.0   0.1   0.0  0.0   63.31  0.06  6.47  -0.11  -0.0    0.03  -0.1   0.17  0.0

Min Loss train: 2.88e-01 val: 2.44e-01
 update plot 8




Loss train: 2.88e-01 val: 2.44e-01 grad: 1.77e+01 lr: 2.0e-03 1.0%┣┫ 26/2.5k [00:50<01:22:15, 2s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.19  0.0   0.02  0.0   0.0  0.0   66.47  0.06  6.56  -0.19   0.01  -0.02   0.19  0.01  0.0
  0.08  0.0   0.0   0.11  0.0  0.0   66.64  0.09  7.01  -0.08   0.06   0.02  -0.11  0.11  0.0
  0.16  0.09  0.06  0.0   0.0  0.0   70.53  0.08  7.49  -0.16  -0.09  -0.06   0.25  0.06  0.0
  0.03  0.19  0.07  0.0   0.0  0.0   73.07  0.09  6.77  -0.03  -0.19  -0.07   0.24  0.04  0.0
 -0.0   0.0   0.0   0.17  0.0  0.09  77.9   0.05  6.75   0.0   -0.0    0.15  -0.17  0.03  0.0
  0.04  0.04  0.0   0.0   0.0  0.11  71.23  0.1   6.09  -0.04  -0.04   0.01   0.06  0.0   0.0
 -0.0   0.01  0.0   0.22  0.0  0.06  68.51  0.11  7.17   0.0   -0.01   0.13  -0.22  0.1   0.0
  0.11  0.0   0.0   0.1   0.0  0.0   62.37  0.06  6.39  -0.11   0.0    0.04  -0.1   0.17  0.0

Min Loss train: 2.85e-01 val: 2.04e-01
 update plot 2



Loss train: 2.85e-01 val: 2.04e-01 grad: 2.20e+01 lr: 2.0e-03 1.1%┣┫ 27/2.5k [00:51<01:20:35, 2s/it]
Loss train: 2.76e-01 val: 2.21e-01 grad: 2.50e+01 lr: 2.0e-03 1.1%┣┫ 28/2.5k [00:52<01:18:55, 2s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.19  0.0   0.01  0.0   0.0  0.0   66.27  0.06  6.53  -0.19   0.01  -0.01   0.19  0.01  0.0
  0.08  0.0   0.0   0.12  0.0  0.0   66.37  0.09  6.97  -0.08   0.06   0.02  -0.12  0.11  0.0
  0.17  0.09  0.05  0.0   0.0  0.0   70.01  0.08  7.48  -0.17  -0.09  -0.05   0.25  0.06  0.0
  0.02  0.19  0.07  0.0   0.0  0.01  72.2   0.1   6.78  -0.02  -0.19  -0.07   0.24  0.04  0.0
 -0.0   0.0   0.0   0.18  0.0  0.09  77.5   0.05  6.71   0.0   -0.0    0.15  -0.18  0.03  0.0
  0.04  0.04  0.0   0.0   0.0  0.11  70.98  0.09  6.05  -0.04  -0.04   0.01   0.06  0.0   0.0
 -0.0   0.01  0.0   0.23  0.0  0.07  67.83  0.12  7.15   0.0   -0.01   0.14  -0.23  0.11  0.0
  0.11  0.0   0.0   0.11  0.0  0.0   61.94  0.06  6.37  -0.11   0.0    0.04  -0.11  0.18  0.0

Min Loss train: 2.76e-01 val: 2.00e-01
 update plot 2




Loss train: 2.76e-01 val: 2.00e-01 grad: 2.51e+01 lr: 2.0e-03 1.2%┣┫ 29/2.5k [00:53<01:17:42, 2s/it]
Loss train: 2.89e-01 val: 2.69e-01 grad: 2.63e+01 lr: 2.0e-03 1.2%┣┫ 30/2.5k [00:54<01:16:14, 2s/it]
Loss train: 2.70e-01 val: 2.01e-01 grad: 2.49e+01 lr: 2.0e-03 1.2%┣┫ 31/2.5k [00:55<01:14:59, 2s/it]
Loss train: 2.66e-01 val: 2.11e-01 grad: 2.32e+01 lr: 2.0e-03 1.3%┣┫ 32/2.5k [00:56<01:13:45, 2s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.21  0.0   0.01  0.0   0.0  0.0   66.29  0.06  6.53  -0.21   0.01  -0.01   0.2   0.01  0.0
  0.08  0.0   0.0   0.13  0.0  0.0   66.44  0.09  6.97  -0.08   0.07   0.03  -0.13  0.12  0.0
  0.18  0.1   0.05  0.0   0.0  0.0   69.65  0.09  7.53  -0.18  -0.1   -0.05   0.26  0.07  0.0
  0.02  0.2   0.08  0.0   0.0  0.02  72.0   0.1   6.78  -0.02  -0.2   -0.08   0.26  0.04  0.0
 -0.0   0.0   0.0   0.19  0.0  0.1   77.24  0.05  6.72   0.0   -0.0    0.16  -0.19  0.03  0.0
  0.04  0.04  0.0   0.0   0.0  0.11  71.25  0.09  6.01  -0.04  -0.04   0.01   0.06  0.0   0.0
 -0.0   0.02  0.0   0.24  0.0  0.08  67.22  0.12  7.19   0.0   -0.02   0.15  -0.24  0.11  0.0
  0.11  0.0   0.0   0.13  0.0  0.0   61.83  0.07  6.39  -0.11   0.01   0.04  -0.13  0.19  0.0

Min Loss train: 2.64e-01 val: 1.87e-01
 update plot 1



Loss train: 2.64e-01 val: 1.87e-01 grad: 2.81e+01 lr: 2.0e-03 1.3%┣┫ 33/2.5k [00:57<01:12:47, 2s/it]
Loss train: 2.65e-01 val: 2.32e-01 grad: 2.48e+01 lr: 2.0e-03 1.4%┣┫ 34/2.5k [00:58<01:11:51, 2s/it]
Loss train: 2.59e-01 val: 2.21e-01 grad: 1.92e+01 lr: 2.0e-03 1.4%┣┫ 35/2.5k [00:59<01:10:50, 2s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.21  0.0   0.01  0.0   0.0  0.0   66.44  0.06  6.53  -0.21   0.01  -0.01   0.21  0.01  0.0
  0.08  0.0   0.0   0.14  0.0  0.0   66.47  0.09  6.98  -0.08   0.07   0.03  -0.14  0.12  0.0
  0.19  0.1   0.06  0.0   0.0  0.0   69.39  0.09  7.57  -0.19  -0.1   -0.06   0.27  0.08  0.0
  0.02  0.21  0.08  0.0   0.0  0.03  71.86  0.1   6.79  -0.02  -0.21  -0.08   0.27  0.04  0.0
 -0.0   0.0   0.0   0.2   0.0  0.1   77.09  0.05  6.72   0.0   -0.0    0.17  -0.2   0.03  0.0
  0.04  0.04  0.0   0.0   0.0  0.12  71.42  0.09  5.99  -0.04  -0.04   0.01   0.07  0.0   0.0
 -0.0   0.02  0.0   0.25  0.0  0.09  66.72  0.12  7.23   0.0   -0.02   0.16  -0.25  0.11  0.0
  0.11  0.0   0.0   0.15  0.0  0.0   61.76  0.07  6.4   -0.11   0.01   0.04  -0.15  0.2   0.0

Min Loss train: 2.58e-01 val: 1.76e-01
 update plot 3



Loss train: 2.58e-01 val: 1.76e-01 grad: 2.68e+01 lr: 2.0e-03 1.4%┣┫ 36/2.5k [01:00<01:10:10, 2s/it]
Loss train: 2.52e-01 val: 1.98e-01 grad: 2.66e+01 lr: 2.0e-03 1.5%┣┫ 37/2.5k [01:01<01:09:09, 2s/it]
Loss train: 2.57e-01 val: 2.31e-01 grad: 2.41e+01 lr: 2.0e-03 1.5%┣┫ 38/2.5k [01:02<01:08:13, 2s/it]
Loss train: 2.44e-01 val: 1.85e-01 grad: 2.38e+01 lr: 2.0e-03 1.6%┣┫ 39/2.5k [01:02<01:07:22, 2s/it]
Loss train: 2.40e-01 val: 1.88e-01 grad: 2.69e+01 lr: 2.0e-03 1.6%┣┫ 40/2.5k [01:03<01:06:42, 2s/it]
Loss train: 2.37e-01 val: 1.93e-01 grad: 2.58e+01 lr: 2.0e-03 1.6%┣┫ 41/2.5k [01:04<01:06:02, 2s/it]
Loss train: 2.33e-01 val: 1.93e-01 grad: 2.68e+01 lr: 2.0e-03 1.7%┣┫ 42/2.5k [01:05<01:05:25, 2s/it]
Loss train: 2.37e-01 val: 2.16e-01 grad: 2.09e+01 lr: 2.0e-03 1.7%┣┫ 43/2.5k [01:06<01:04:48, 2s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.22  0.0   0.01  0.0   0.0  0.0   66.45  0.06  6.45  -0.22   0.0   -0.01   0.22  0.01  0.0
  0.08  0.0   0.0   0.17  0.0  0.0   65.9   0.1   6.94  -0.08   0.08   0.03  -0.17  0.14  0.0
  0.21  0.09  0.07  0.0   0.0  0.0   68.0   0.11  7.61  -0.21  -0.09  -0.07   0.29  0.09  0.0
  0.01  0.2   0.1   0.0   0.0  0.05  70.96  0.1   6.74  -0.01  -0.2   -0.1    0.28  0.04  0.0
 -0.0   0.0   0.0   0.22  0.0  0.12  75.96  0.05  6.69   0.0   -0.0    0.19  -0.22  0.04  0.0
  0.04  0.05  0.0   0.0   0.0  0.12  71.05  0.08  5.92  -0.04  -0.05   0.01   0.08  0.0   0.0
 -0.0   0.02  0.0   0.25  0.0  0.12  64.42  0.14  7.3    0.0   -0.02   0.18  -0.25  0.1   0.0
  0.11  0.0   0.0   0.18  0.0  0.0   61.02  0.07  6.4   -0.11   0.03   0.04  -0.18  0.22  0.0

Min Loss train: 2.33e-01 val: 1.71e-01
 update plot 6




Loss train: 2.39e-01 val: 1.71e-01 grad: 2.30e+01 lr: 2.0e-03 1.8%┣┫ 44/2.5k [01:08<01:04:22, 2s/it]
Loss train: 2.32e-01 val: 2.19e-01 grad: 2.35e+01 lr: 2.0e-03 1.8%┣┫ 45/2.5k [01:09<01:03:58, 2s/it]
Loss train: 2.21e-01 val: 1.89e-01 grad: 2.53e+01 lr: 2.0e-03 1.8%┣┫ 46/2.5k [01:10<01:03:29, 2s/it]
Loss train: 2.23e-01 val: 2.12e-01 grad: 1.83e+01 lr: 2.0e-03 1.9%┣┫ 47/2.5k [01:11<01:03:03, 2s/it]
Loss train: 2.15e-01 val: 1.93e-01 grad: 1.89e+01 lr: 2.0e-03 1.9%┣┫ 48/2.5k [01:12<01:02:40, 2s/it]
Loss train: 2.16e-01 val: 1.97e-01 grad: 2.74e+01 lr: 2.0e-03 2.0%┣┫ 49/2.5k [01:13<01:02:20, 2s/it]
Loss train: 2.15e-01 val: 2.20e-01 grad: 1.89e+01 lr: 2.0e-03 2.0%┣┫ 50/2.5k [01:14<01:01:58, 2s/it]
Loss train: 2.08e-01 val: 2.05e-01 grad: 1.87e+01 lr: 2.0e-03 2.0%┣┫ 51/2.5k [01:16<01:01:39, 2s/it]
Loss train: 2.14e-01 val: 2.22e-01 grad: 2.25e+01 lr: 2.0e-03 2.1%┣┫ 52/2.5k [01:17<01:01:23, 2s/it]
Loss train: 2.02e-01 val: 2.15e-01 grad: 1.55e+01 lr: 2.0e-03 2.1%┣┫ 53/2.5k [01:18<01:01:


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.28  0.0   0.0   0.0   0.0  0.0    93.25  0.06   8.73  -0.28   0.01  -0.0    0.26  0.01  0.0
  0.09  0.0   0.0   0.29  0.0  0.0    86.55  0.15  10.04  -0.09   0.15   0.04  -0.29  0.18  0.0
  0.41  0.08  0.07  0.0   0.0  0.0    88.75  0.24  11.77  -0.41  -0.08  -0.07   0.4   0.15  0.0
 -0.0   0.33  0.16  0.0   0.0  0.02   86.38  0.16   9.9    0.0   -0.33  -0.16   0.47  0.02  0.0
 -0.0   0.0   0.0   0.34  0.0  0.14  103.79  0.03   8.82   0.0   -0.0    0.27  -0.34  0.07  0.0
  0.05  0.06  0.03  0.0   0.0  0.17   99.65  0.05   7.63  -0.05  -0.06  -0.03   0.13  0.0   0.0
 -0.0   0.0   0.0   0.47  0.0  0.17   74.42  0.19  10.5    0.0    0.02   0.3   -0.47  0.15  0.0
  0.11  0.0   0.0   0.39  0.0  0.0    76.39  0.18   9.97  -0.11   0.1    0.08  -0.39  0.33  0.0

Min Loss train: 1.25e-01 val: 1.37e-01
 update plot 3



Loss train: 1.82e-01 val: 1.37e-01 grad: 1.86e+01 lr: 2.0e-03 8.4%┣┫ 209/2.5k [04:14<46:42, 1s/it]
Loss train: 2.03e-01 val: 2.28e-01 grad: 1.94e+01 lr: 2.0e-03 8.4%┣┫ 210/2.5k [04:15<46:39, 1s/it]
Loss train: 1.37e-01 val: 1.76e-01 grad: 1.50e+01 lr: 2.0e-03 8.4%┣┫ 211/2.5k [04:16<46:35, 1s/it]
Loss train: 1.55e-01 val: 1.69e-01 grad: 2.44e+01 lr: 2.0e-03 8.5%┣┫ 212/2.5k [04:18<46:32, 1s/it]
Loss train: 1.52e-01 val: 1.85e-01 grad: 1.65e+01 lr: 2.0e-03 8.5%┣┫ 213/2.5k [04:19<46:29, 1s/it]
Loss train: 1.33e-01 val: 1.71e-01 grad: 1.45e+01 lr: 2.0e-03 8.6%┣┫ 214/2.5k [04:20<46:26, 1s/it]
Loss train: 1.39e-01 val: 1.67e-01 grad: 1.75e+01 lr: 2.0e-03 8.6%┣┫ 215/2.5k [04:21<46:24, 1s/it]
Loss train: 1.34e-01 val: 1.99e-01 grad: 1.11e+01 lr: 2.0e-03 8.6%┣┫ 216/2.5k [04:22<46:23, 1s/it]
Loss train: 1.27e-01 val: 1.95e-01 grad: 1.04e+01 lr: 2.0e-03 8.7%┣┫ 217/2.5k [04:23<46:20, 1s/it]
Loss train: 1.84e-01 val: 1.39e-01 grad: 1.52e+01 lr: 2.0e-03 8.7%┣┫ 218/2.5k [04:24<46:18, 1s/it]
Loss train


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.29  0.0   0.0   0.0   0.0  0.0   102.19  0.06   9.64  -0.29   0.02   0.0    0.26  0.01  0.0
  0.09  0.0   0.0   0.3   0.0  0.0    93.61  0.16  11.25  -0.09   0.16   0.04  -0.3   0.18  0.0
  0.43  0.07  0.07  0.0   0.0  0.0    97.51  0.26  13.27  -0.43  -0.07  -0.07   0.41  0.17  0.0
 -0.0   0.37  0.18  0.0   0.0  0.05   91.85  0.17  11.17   0.0   -0.37  -0.18   0.51  0.04  0.0
 -0.0   0.0   0.0   0.35  0.0  0.14  114.2   0.02   9.67   0.0   -0.0    0.28  -0.35  0.08  0.0
  0.05  0.06  0.03  0.0   0.0  0.17  109.54  0.05   8.38  -0.05  -0.06  -0.03   0.13  0.0   0.0
 -0.0   0.0   0.0   0.49  0.0  0.19   78.43  0.2   11.73   0.0    0.01   0.31  -0.49  0.17  0.0
  0.12  0.0   0.0   0.43  0.0  0.0    81.79  0.21  11.36  -0.12   0.12   0.09  -0.43  0.34  0.0

Min Loss train: 1.14e-01 val: 1.03e-01
 update plot 1



Loss train: 1.89e-01 val: 1.03e-01 grad: 1.36e+01 lr: 2.0e-03 11.1%┣┫ 278/2.5k [05:27<43:43, 1s/it]
Loss train: 1.49e-01 val: 2.14e-01 grad: 2.39e+01 lr: 2.0e-03 11.2%┣┫ 279/2.5k [05:28<43:42, 1s/it]
Loss train: 1.59e-01 val: 1.87e-01 grad: 1.30e+01 lr: 2.0e-03 11.2%┣┫ 280/2.5k [05:29<43:39, 1s/it]
Loss train: 1.65e-01 val: 1.74e-01 grad: 1.59e+01 lr: 2.0e-03 11.2%┣┫ 281/2.5k [05:30<43:37, 1s/it]
Loss train: 1.53e-01 val: 1.63e-01 grad: 1.69e+01 lr: 2.0e-03 11.3%┣┫ 282/2.5k [05:31<43:35, 1s/it]
Loss train: 1.28e-01 val: 1.89e-01 grad: 1.72e+01 lr: 2.0e-03 11.3%┣┫ 283/2.5k [05:32<43:32, 1s/it]
Loss train: 1.23e-01 val: 1.81e-01 grad: 1.08e+01 lr: 2.0e-03 11.4%┣┫ 284/2.5k [05:33<43:30, 1s/it]
Loss train: 1.19e-01 val: 1.64e-01 grad: 8.70e+00 lr: 2.0e-03 11.4%┣┫ 285/2.5k [05:34<43:28, 1s/it]
Loss train: 1.15e-01 val: 1.76e-01 grad: 1.55e+01 lr: 2.0e-03 11.4%┣┫ 286/2.5k [05:35<43:26, 1s/it]
Loss train: 1.13e-01 val: 1.69e-01 grad: 1.02e+01 lr: 2.0e-03 11.5%┣┫ 287/2.5k [05:36<43:24, 1s/it]



 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.3   0.0   0.0   0.0   0.0  0.0   140.17  0.06  13.33  -0.3    0.02  -0.0    0.27  0.01  0.0
  0.1   0.0   0.0   0.31  0.0  0.02  123.3   0.19  16.16  -0.1    0.2    0.03  -0.31  0.18  0.0
  0.57  0.11  0.04  0.0   0.0  0.04  129.74  0.35  19.98  -0.57  -0.11  -0.04   0.48  0.24  0.0
 -0.0   0.42  0.27  0.0   0.0  0.04  114.42  0.21  16.2    0.0   -0.42  -0.27   0.46  0.23  0.0
 -0.0   0.0   0.0   0.36  0.0  0.14  157.5   0.02  13.27   0.0   -0.0    0.28  -0.36  0.08  0.0
  0.05  0.06  0.03  0.0   0.0  0.17  150.87  0.05  11.52  -0.05  -0.06  -0.03   0.13  0.0   0.0
 -0.0   0.0   0.0   0.65  0.0  0.25   96.18  0.24  16.91   0.0    0.06   0.32  -0.65  0.26  0.0
  0.1   0.0   0.0   0.57  0.0  0.02  104.83  0.28  16.85  -0.1    0.18   0.1   -0.57  0.39  0.0

Min Loss train: 8.86e-02 val: 8.77e-02
 update plot 9




Loss train: 1.22e-01 val: 8.77e-02 grad: 1.03e+01 lr: 1.0e-03 34.1%┣┫ 852/2.5k [15:42<30:25, 1s/it]
Loss train: 1.01e-01 val: 1.33e-01 grad: 1.82e+01 lr: 1.0e-03 34.1%┣┫ 853/2.5k [15:43<30:24, 1s/it]
Loss train: 1.12e-01 val: 1.27e-01 grad: 1.11e+01 lr: 1.0e-03 34.2%┣┫ 854/2.5k [15:44<30:22, 1s/it]
Loss train: 1.05e-01 val: 1.17e-01 grad: 1.30e+01 lr: 1.0e-03 34.2%┣┫ 855/2.5k [15:45<30:21, 1s/it]
Loss train: 9.65e-02 val: 1.24e-01 grad: 1.26e+01 lr: 1.0e-03 34.2%┣┫ 856/2.5k [15:46<30:20, 1s/it]
Loss train: 9.15e-02 val: 1.35e-01 grad: 1.09e+01 lr: 1.0e-03 34.3%┣┫ 857/2.5k [15:47<30:19, 1s/it]
Loss train: 9.26e-02 val: 1.37e-01 grad: 8.92e+00 lr: 1.0e-03 34.3%┣┫ 858/2.5k [15:48<30:17, 1s/it]
Loss train: 9.06e-02 val: 1.33e-01 grad: 8.82e+00 lr: 1.0e-03 34.4%┣┫ 859/2.5k [15:50<30:16, 1s/it]
Loss train: 1.01e-01 val: 1.16e-01 grad: 1.27e+01 lr: 1.0e-03 34.4%┣┫ 860/2.5k [15:51<30:15, 1s/it]
Loss train: 8.92e-02 val: 1.34e-01 grad: 1.22e+01 lr: 1.0e-03 34.4%┣┫ 861/2.5k [15:52<30:14, 1s/it]


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.3   0.0   0.0   0.0   0.0  0.0   162.2   0.06  15.4   -0.3    0.02  -0.0    0.27  0.01  0.0
  0.11  0.0   0.0   0.35  0.0  0.01  139.5   0.2   18.89  -0.11   0.26   0.01  -0.35  0.18  0.0
  0.69  0.17  0.03  0.0   0.0  0.11  145.31  0.41  24.28  -0.69  -0.17  -0.03   0.61  0.28  0.0
 -0.0   0.44  0.25  0.0   0.0  0.07  124.81  0.2   18.77   0.0   -0.44  -0.25   0.47  0.22  0.0
 -0.0   0.0   0.0   0.36  0.0  0.15  182.26  0.02  15.33   0.0   -0.0    0.28  -0.36  0.08  0.0
  0.05  0.06  0.03  0.0   0.0  0.17  174.52  0.05  13.31  -0.05  -0.06  -0.03   0.14  0.0   0.0
 -0.0   0.0   0.0   0.76  0.0  0.32  102.36  0.27  20.23   0.0    0.16   0.27  -0.76  0.33  0.0
  0.08  0.0   0.0   0.68  0.0  0.0   116.1   0.3   19.98  -0.08   0.23   0.09  -0.68  0.43  0.0

Min Loss train: 7.60e-02 val: 8.69e-02
 update plot 1


Loss train: 7.99e-02 val: 8.69e-02 grad: 1.03e+01 lr: 2.5e-04 63.8%┣┫ 1.6k/2.5k [29:03<16:32, 1s/it]
Loss train: 8.25e-02 val: 1.01e-01 grad: 1.54e+01 lr: 2.5e-04 63.8%┣┫ 1.6k/2.5k [29:05<16:31, 1s/it]
Loss train: 8.92e-02 val: 1.08e-01 grad: 8.50e+00 lr: 2.5e-04 63.8%┣┫ 1.6k/2.5k [29:06<16:29, 1s/it]
Loss train: 8.58e-02 val: 1.05e-01 grad: 8.55e+00 lr: 2.5e-04 63.9%┣┫ 1.6k/2.5k [29:07<16:28, 1s/it]
Loss train: 8.35e-02 val: 1.06e-01 grad: 9.24e+00 lr: 2.5e-04 63.9%┣┫ 1.6k/2.5k [29:08<16:27, 1s/it]
Loss train: 8.22e-02 val: 1.03e-01 grad: 1.01e+01 lr: 2.5e-04 64.0%┣┫ 1.6k/2.5k [29:09<16:26, 1s/it]
Loss train: 7.94e-02 val: 1.06e-01 grad: 9.80e+00 lr: 2.5e-04 64.0%┣┫ 1.6k/2.5k [29:10<16:25, 1s/it]
Loss train: 8.10e-02 val: 1.10e-01 grad: 1.01e+01 lr: 2.5e-04 64.0%┣┫ 1.6k/2.5k [29:11<16:24, 1s/it]
Loss train: 7.82e-02 val: 1.05e-01 grad: 8.31e+00 lr: 2.5e-04 64.1%┣┫ 1.6k/2.5k [29:12<16:23, 1s/it]
Loss train: 7.82e-02 val: 1.03e-01 grad: 9.66e+00 lr: 2.5e-04 64.1%┣┫ 1.6k/2.5k [29:13<16:2


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.3   0.0   0.0   0.0   0.0  0.0   170.64  0.06  16.19  -0.3    0.02  -0.0    0.27  0.01  0.0
  0.11  0.0   0.0   0.36  0.0  0.01  146.58  0.2   19.82  -0.11   0.29  -0.0   -0.36  0.18  0.0
  0.74  0.2   0.02  0.0   0.0  0.14  150.82  0.42  25.95  -0.74  -0.2   -0.02   0.67  0.28  0.0
 -0.0   0.45  0.23  0.0   0.0  0.08  127.76  0.19  19.6    0.0   -0.45  -0.23   0.48  0.2   0.0
 -0.0   0.0   0.0   0.36  0.0  0.15  191.72  0.02  16.12   0.0   -0.0    0.28  -0.36  0.08  0.0
  0.04  0.06  0.03  0.0   0.0  0.17  183.56  0.05  14.0   -0.04  -0.06  -0.03   0.14  0.0   0.0
 -0.0   0.0   0.0   0.81  0.0  0.34  104.48  0.28  21.49   0.0    0.19   0.25  -0.81  0.36  0.0
  0.07  0.0   0.0   0.7   0.0  0.0   120.13  0.3   21.18  -0.07   0.25   0.08  -0.7   0.44  0.0

Min Loss train: 7.17e-02 val: 7.81e-02
 update plot 4



Loss train: 8.11e-02 val: 7.81e-02 grad: 8.14e+00 lr: 2.5e-04 76.8%┣┫ 1.9k/2.5k [34:59<10:34, 1s/it]
Loss train: 8.28e-02 val: 1.00e-01 grad: 1.35e+01 lr: 2.5e-04 76.8%┣┫ 1.9k/2.5k [35:00<10:33, 1s/it]
Loss train: 8.59e-02 val: 9.95e-02 grad: 9.89e+00 lr: 2.5e-04 76.9%┣┫ 1.9k/2.5k [35:01<10:32, 1s/it]
Loss train: 8.50e-02 val: 1.06e-01 grad: 8.92e+00 lr: 2.5e-04 76.9%┣┫ 1.9k/2.5k [35:02<10:31, 1s/it]
Loss train: 7.73e-02 val: 1.03e-01 grad: 7.17e+00 lr: 2.5e-04 77.0%┣┫ 1.9k/2.5k [35:03<10:30, 1s/it]
Loss train: 7.61e-02 val: 1.03e-01 grad: 9.50e+00 lr: 2.5e-04 77.0%┣┫ 1.9k/2.5k [35:04<10:29, 1s/it]
Loss train: 7.64e-02 val: 1.02e-01 grad: 9.07e+00 lr: 2.5e-04 77.0%┣┫ 1.9k/2.5k [35:05<10:28, 1s/it]
Loss train: 7.51e-02 val: 1.08e-01 grad: 1.00e+01 lr: 2.5e-04 77.1%┣┫ 1.9k/2.5k [35:06<10:27, 1s/it]
Loss train: 7.49e-02 val: 1.07e-01 grad: 7.26e+00 lr: 2.5e-04 77.1%┣┫ 1.9k/2.5k [35:07<10:25, 1s/it]
Loss train: 7.37e-02 val: 9.96e-02 grad: 9.00e+00 lr: 2.5e-04 77.2%┣┫ 1.9k/2.5k [35:08<10:2


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
  0.3   0.0   0.0   0.0   0.0  0.0   174.19  0.06  16.52  -0.3    0.02  -0.0    0.27  0.01  0.0
  0.11  0.0   0.01  0.34  0.0  0.01  148.72  0.2   20.28  -0.11   0.29  -0.01  -0.34  0.18  0.0
  0.76  0.21  0.01  0.0   0.0  0.16  153.22  0.43  26.68  -0.76  -0.21  -0.01   0.69  0.28  0.0
 -0.0   0.45  0.22  0.0   0.0  0.09  128.63  0.18  19.94   0.0   -0.45  -0.22   0.5   0.17  0.0
 -0.0   0.0   0.0   0.36  0.0  0.15  195.71  0.02  16.45   0.0   -0.0    0.28  -0.36  0.08  0.0
  0.04  0.06  0.03  0.0   0.0  0.17  187.36  0.05  14.29  -0.04  -0.06  -0.03   0.14  0.0   0.0
 -0.0   0.0   0.0   0.85  0.0  0.35  104.75  0.29  22.06   0.0    0.21   0.25  -0.85  0.38  0.0
  0.07  0.0   0.0   0.71  0.0  0.0   121.43  0.31  21.71  -0.07   0.26   0.07  -0.71  0.45  0.0

Min Loss train: 6.88e-02 val: 6.36e-02
 update plot 7



Loss train: 8.68e-02 val: 6.36e-02 grad: 9.08e+00 lr: 1.3e-04 84.8%┣┫ 2.1k/2.5k [38:39<06:56, 1s/it]
Loss train: 7.72e-02 val: 9.65e-02 grad: 1.65e+01 lr: 1.3e-04 84.8%┣┫ 2.1k/2.5k [38:40<06:55, 1s/it]
Loss train: 8.26e-02 val: 9.34e-02 grad: 7.12e+00 lr: 1.3e-04 84.9%┣┫ 2.1k/2.5k [38:41<06:54, 1s/it]
Loss train: 7.90e-02 val: 9.38e-02 grad: 8.77e+00 lr: 1.3e-04 84.9%┣┫ 2.1k/2.5k [38:42<06:52, 1s/it]
Loss train: 7.56e-02 val: 9.51e-02 grad: 8.23e+00 lr: 1.3e-04 85.0%┣┫ 2.1k/2.5k [38:43<06:51, 1s/it]
Loss train: 7.40e-02 val: 1.01e-01 grad: 7.23e+00 lr: 1.3e-04 85.0%┣┫ 2.1k/2.5k [38:44<06:50, 1s/it]
Loss train: 7.25e-02 val: 1.02e-01 grad: 7.60e+00 lr: 1.3e-04 85.0%┣┫ 2.1k/2.5k [38:45<06:49, 1s/it]
Loss train: 7.33e-02 val: 9.83e-02 grad: 8.87e+00 lr: 1.3e-04 85.1%┣┫ 2.1k/2.5k [38:46<06:48, 1s/it]
Loss train: 7.19e-02 val: 1.01e-01 grad: 8.88e+00 lr: 1.3e-04 85.1%┣┫ 2.1k/2.5k [38:47<06:47, 1s/it]
Loss train: 7.16e-02 val: 9.82e-02 grad: 8.85e+00 lr: 1.3e-04 85.2%┣┫ 2.1k/2.5k [38:48<06:4

In [323]:
expr_name = "5s8r1c-01"
fig_path = string("./results_catalyst/", expr_name, "/figs")
ckpt_path = string("./results_catalyst/", expr_name, "/checkpoint")
@load string(ckpt_path, "/mymodel.bson") p #opt l_loss_train l_loss_val list_grad iter

#p[9] = -2
p_cutoff = 0.0

display_p(p)

for i_exp = 1:n_exp
    cbi(p, i_exp)
end

loss_epoch = zeros(Float64, n_exp);
for i_exp = 1:n_exp
    loss_epoch[i_exp] = loss_neuralode(p, i_exp)
end
loss_train = mean(loss_epoch[l_train])
loss_val = mean(loss_epoch[l_val])
loss_train, loss_val


 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×15 Matrix{Float64}:
 -0.0   0.54  0.01  0.0   0.0  0.0   80.24  0.14   9.29   0.0   -0.54  -0.01   0.5   0.05  0.0
  0.33  0.19  0.05  0.0   0.0  0.01  72.31  0.25   9.66  -0.33  -0.19  -0.05   0.48  0.09  0.0
  0.39  0.0   0.0   0.0   0.0  0.25  95.21  0.24  11.09  -0.39   0.27   0.01   0.1   0.0   0.0
 -0.0   0.0   0.0   0.52  0.0  0.15  89.59  0.14   9.54   0.0    0.13   0.32  -0.52  0.08  0.0
 -0.0   0.0   0.0   0.65  0.0  0.0   77.4   0.27  11.19   0.0    0.41  -0.0   -0.65  0.24  0.0
  0.12  0.0   0.0   0.36  0.0  0.01  91.15  0.28  11.15  -0.12   0.35  -0.0   -0.36  0.12  0.0
 -0.0   0.0   0.0   0.47  0.0  0.07  63.42  0.13   9.59   0.0    0.07   0.17  -0.47  0.23  0.0
  0.29  0.0   0.01  0.0   0.0  0.08  98.2   0.13   9.39  -0.29   0.07  -0.01   0.23  0.01  0.0



(0.08336832189868705, 0.0822633956374589)

In [30]:
# pyplot()
plot_loss(l_loss_train, l_loss_val; yscale = :log10)

"./results_cat3/7s8r1c-08/figs\\loss_grad.png"

In [218]:
function loss_neuralode_res(p)
    l_loss_exp = zeros(n_exp)
    for i_exp in 1:n_exp
        exp_data = l_exp_data[i_exp]
        pred = Array(pred_n_ode(p, i_exp, exp_data))
        masslist = sum(clamp.(@view(pred[1:end-1, :]), 0, Inf), dims = 1)'
        l_loss_exp[i_exp] = mae(masslist, @view(exp_data[1:length(masslist), 3]))
    end
    return l_loss_exp
end

loss_neuralode_res (generic function with 1 method)

In [203]:
println("results after pruning")
maxiters = 1e5
p_cutoff = 0.0

results after pruning


0.0

In [221]:
loss_epoch = zeros(Float64, n_exp);
for i_exp = 1:n_exp
    loss_epoch[i_exp] = loss_neuralode(p, i_exp)
end
loss_train = mean(loss_epoch[l_train])
loss_val = mean(loss_epoch[l_val])
@printf(
    "Loss train: %.2f val: %.2f p_cutoff: %.2e",
    log10(loss_train),
    log10(loss_val),
    p_cutoff
)

display_p(p)

Loss train: -0.59 val: -0.58 p_cutoff: 1.85e-01
 species (column) reaction (row)
w_in | w_cat_in | Ea | b | lnA | w_out | w_cat_out
8×19 Matrix{Float64}:
 -0.0   -0.0  -0.0   -0.0   -0.0  0.0   -0.0  0.0   289.36  0.12  26.97   0.0   0.0   0.0    0.0    0.0   -0.0   0.0   0.0
  1.75  -0.0  -0.0   -0.0    0.0  0.0   -0.0  0.19  238.25  0.56  44.6   -1.75  0.0   0.0    0.0    0.52   1.23  0.0   0.0
 -0.0   -0.0   0.68  -0.0   -0.0  0.0    0.0  0.35  251.77  0.45  43.44   0.0   0.0  -0.68   0.0    0.0    0.1   0.59  0.0
 -0.0   -0.0  -0.0   -0.0   -0.0  0.0   -0.0  0.19  263.4   0.08  28.33   0.0   0.0   0.0    0.0    0.0   -0.0   0.0   0.0
 -0.0   -0.0  -0.0    0.21   0.0  1.21   0.0  0.01  261.82  0.71  49.65   0.0   0.0   0.0   -0.21   0.28  -1.21  1.13  0.0
 -0.0   -0.0   0.21  -0.0    0.6  0.0   -0.0  0.07  279.12  0.67  49.71   0.0   0.0  -0.21   0.0   -0.6    0.81  0.0   0.0
 -0.0   -0.0   0.0   -0.0    0.0  0.53  -0.0  0.16  127.97  0.0   25.21   0.0   0.0   0.27   0.0    0.26  -0

In [222]:
for i_exp in randperm(n_exp)
    cbi(p, i_exp)
end

In [223]:
l_loss_exp = loss_neuralode_res(p)

18-element Vector{Float64}:
 0.5731249928232994
 0.573818698550572
 0.5599319238596631
 0.6038493091687965
 0.6018047217616849
 0.6049788272576078
 0.5073004092208907
 0.42357193899865203
 0.4033434698914744
 0.4233822601722467
 0.5204082517584994
 0.4756764430372351
 0.5732156460521934
 0.5729433777049404
 0.5785797501762748
 0.5167738478487672
 0.5376574507332098
 0.5233036501654168

In [226]:
l_exp_data = []
l_exp_info = zeros(Float64, length(l_exp), 3)
for (i_exp, value) in enumerate(l_exp)
    filename = string("exp_data_cat3/expdata_no", string(value), ".txt")
    exp_data = Float64.(load_exp(filename))
    push!(l_exp_data, exp_data)
    l_exp_info[i_exp, 1] = exp_data[1, 2] # initial temperature, K
end
l_exp_info[:, 2] = readdlm("exp_data_cat3/beta.txt")[l_exp]
#l_exp_info[:, 3] = log.(readdlm("exp_data_cat3/ocen.txt")[l_exp] .+ llb)
l_exp_info[:, 3] = (readdlm("exp_data_cat3/cata_conc.txt")[l_exp]);

l_loss_exp = loss_neuralode_res(p)

conc_end = zeros(n_exp, ns)

18×8 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
# Plot TGA data
list_plt = []
for i_exp = 1:18
    T0, beta, cata_conc = l_exp_info[i_exp, :]
    exp_data = l_exp_data[i_exp]
    sol = pred_n_ode(p, i_exp, exp_data)
    Tlist = similar(sol.t)
    T0, beta, cata_conc = l_exp_info[i_exp, :]
    for (i, t) in enumerate(sol.t)
        Tlist[i] = getsampletemp(t, T0, beta)
    end

    conc_end[i_exp, :] .= sol[:, end]

    plt = plot(
        Tlist,
        exp_data[:, 3],
        seriestype = :scatter,
        label = "Exp-$i_exp",
        framestyle = :box,
    )
    plot!(
        plt,
        Tlist,
        sum(sol[1:end-1, :], dims = 1)',
        lw = 2,
        legend = false,
    )
    xlabel!(plt, "Temperature [K]")

    exp_cond = @sprintf("T0:%.0f K", T0)
    exp_cond *= @sprintf("\nbeta:%.0f K/min", beta)

    ann_loc = [0.2, 0.3]
    if i_exp in [6, 7, 14]
        ann_loc = [0.7, 0.4]
    end
    annotate!(plt, xlims(plt)[1] + (xlims(plt)[end] - xlims(plt)[1]) * ann_loc[1],
                   ylims(plt)[1] + (ylims(plt)[end] - ylims(plt)[1]) * ann_loc[2],
                   text(exp_cond, 11))

    ylabel!(plt, "Mass [-] (No. $i_exp)")
    ylims!(plt, (0.0, 1.0))
    plot!(
        plt,
        xtickfontsize = 11,
        ytickfontsize = 11,
        xguidefontsize = 12,
        yguidefontsize = 12,
    )

    push!(list_plt, plt)
end

In [ ]:
plt_all = plot(list_plt..., layout = (7, 2))
plot!(plt_all, size = (800, 1200))
png(plt_all, string(fig_path, "/TGA_mass_summary"))

In [ ]:
# https://github.com/DENG-MIT/Biomass.jl/blob/main/backup/crnn_cellulose_ocen_test.jl
varnames = ["Cellu", "S2", "S3", "Vola"]
for i_exp in 1:n_exp
    T0, beta, ocen = l_exp_info[i_exp, :]
    exp_data = l_exp_data[i_exp]
    sol = pred_n_ode(p, i_exp, exp_data)
    Tlist = similar(sol.t)
    T0, beta, ocen = l_exp_info[i_exp, :]
    for (i, t) in enumerate(sol.t)
        Tlist[i] = getsampletemp(t, T0, beta)
    end
    value = l_exp[i_exp]
    list_plt = []
    scale_factor = 1 ./ maximum(sol[:, :], dims=2)
    scale_factor .= 1.0
    plt = plot(Tlist, clamp.(sol[1, :], 0, Inf), label = varnames[1])
    for i in 2:ns
        if scale_factor[i] > 1.1
            _label =  @sprintf("%s x %.2e", varnames[i], scale_factor[i])
        else
            _label = varnames[i]
        end
        plot!(plt, Tlist, clamp.(sol[i, :], 0, Inf) * scale_factor[i], label = _label)
    end
    xlabel!(plt, "Temperature [K]");
    ylabel!(plt, "Mass (-)");
    plot!(plt, size=(350, 350), legend=:topleft, framestyle=:box)
    plot!(
        plt,
        xtickfontsize = 11,
        ytickfontsize = 11,
        xguidefontsize = 12,
        yguidefontsize = 12,
    )
    png(plt, string(fig_path, "/pred_S_exp_$value"))
end

include("dataset.jl")
gr()